name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    required: false
    description: 'todo'
    default: '${{ github.token }}'
  flag-name:
    required: false
    description: 'todo'
runs:
  using: 'node12'
  main: 'dist/index.js'
