name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  repo-token:
    required: false
    description: 'todo'
    default: '${{ github.token }}'
  flag-name:
    required: false
    description: 'todo'
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
